language: cpp

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports # for cmake
    packages:
      - cmake
      - cmake-data

matrix:
  include:
    # Linux GCC
    - os: linux
      compiler: gcc # default Travis CI gcc (4.8.4)
      # (Travis sets CC, CXX)

    # Linux Clang
    - os: linux
      compiler: clang # default Travis CI clang (3.5.0)
      # (Travis sets CC, CXX)

    # Experimental:
    - os: linux
      sudo: required
      language: generic
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']
      env:
        - CXX=clang++-3.8
        - CC=clang-3.8

before_script:
  - ${CXX} --version
  - ${CC} --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j2
  - make CTEST_OUTPUT_ON_FAILURE=1 test

