language: cpp

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports # for cmake
    packages:
      - cmake
      - cmake-data
 
os:
  - linux
 
compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j2
  - make CTEST_OUTPUT_ON_FAILURE=1 test

